from building import *
import os

cwd     = GetCurrentDir()
CPPPATH = [cwd, os.path.join(cwd, 'inc')]
src = Glob('*.c')

group = DefineGroup('HW', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
